language: node_js

node_js: 
  - node # descargará la ultima versión de node

before_script:
  - yarn
  - npm install -g --silent firebase-tools 

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

script:
  - npm run build -- --prod