sudo: required

dist: xenial

language: node_js

node_js: 
  - node # descargará la ultima versión de node

before_script:
  - yarn
  - npm install -g --silent firebase-tools 

script:
  - npm run build -- --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
